sudo: false

notifications:
  email: false

# Only build pushes from the website branch. PRs are always built.
branches:
  only:
    - master

env:
  global:
    # Github Token (GH_TOKEN)
  secure: "YESzqSrWmnFTGXhXliVKlOBleB9fhY37uyKWA+VQIpsbCeei5iRIyeCCVMdMo0jEUAzfTXkhSlC+YEqOyBlT5gfNIy0WIHoKJxc/aZiy3w/+h/BghOsSStRiptnD/2A9Aooqz/pRzAwLO/U1PAsz4p+IhUEE9yGHj9NE8F2conXDh5Pk8gGbD26ZY10gR0q5Pr9AW6mw31F8x3+BmmviLN9X3A8mj25E3R9ZKZw5LkSHUPR20jBtO/wp66Y1GaL07wk+D1RNtB3Cslf54Pvea9snL9hWBK4UvKdu0k4wuzQbi1o7B+E3PVOblXXLH4kt5JkgMSe3gyEnYQMssI3obS582PMDPHGC3hUt/Bh01yazNBagQQtxX84Jj6VA1wO15QQLoL5ZD26Eu3xDrkcwHrCIQXhJbMwIlS6eabLwQdZCc8zWK+9ajq/Z+CAuTyhrvojDaghGm3A8/G/87/Cp3cUX1z39cZ80ZD9kj7bmPMC1W0ke9fFDc7p90t7he2YdMs4JkEBFKeRnXtnIZlbYFZCpFclyi1af/EccLSYe0Ozj36OwJ71Dxzh+4d+0alAteQ14lSJHyL5f/oEOiiVupKwtgqyCOgQq6kzmtdD0056xDY381cl+qoUUQB2miy+BKyh4iVYQHa4+LLYRnlfPjomqJofWrQR8amFN5wrOEwc="

before_install:
  # Get Miniconda from Continuum
  # Need to source the script to set the PATH variable in this environment
  # (not the scripts environment)
  - source ci/install-miniconda.sh

install:
  # Update conda itself
  - conda update --yes conda
  # Create a conda env based on environment.yml
  - conda env create
  - source activate urubu

script:
  - make

deploy:
  # Push the built HMTL to Github pages
  - provider: script
    script: bash ci/deploy-gh-pages.sh
    skip_cleanup: true
    on:
      branch: master

