sudo: false
language: python
python:
    # Python >3.5 is required by doctr
    - 3.6
notifications:
  email: false

# Only build pushes from the master branch. PRs are always built.
branches:
  only:
    - master

env:
  global:
    # Doctr deploy key for santisoler/santisoler.github.io
    - secure: "sr74q7igPRZAvS+CPEAbFgoVdolDnczBO8rIA4P1uN7bPl0C96Bkfi+e16CMRXmTi1EwtdXXruaip9oJolxXKVdBXrjrtPYFJtJkCqWg+abe6ALknqwSwjS25BTbda8GV2Mxus4TfNubRarBdI/Oitc8mdA9gPfs934I9RythEC0HSuwPUnbiBUkglzNyeHHuJDy1wjcQbu3DuKrO4MSE0v5/oN3k3rZyvCfdQ3HIikSzIIIFfNGd0gx+KvvvagiiuIM6bLEc0YNaOn/zqXkmMwE7ZDwECIRSgeTgoBtwq1DCe4UwLEPVMCP7qd+PbrthQ4O7JMXfCA/vlks27ZABNtow+O4zXuvUMUSybuMyRWyntey+9iT9Wm1vttZDleNbn+u0iLXTv52oKm1bngZxPDNP58doyVDEhCe4YooXV19TJy5w8vYWPKjaFKYQFEhsXuEBKUQo7MQn1XcAzTHGwuJdrMKIchY4+zWsh1Urwq1qsF0y/j608ftTf1xijc/Z0OXqyj2qUmEeW7PTsx+jjWmcPFA5RGD9bHjvQBgUe/cq9NscDVb9yCxJR/1kul1YUL10Yjq71FcPmEHAskY/B9I36qY3OQfoaPb/5PVefDrDKfYJ2VwQP9PD9Dn7kE7iQ685IKLUKsPWBFYp69yR6/3I9i7VtrxLhSzX1c0Xl0="

install:
  # Install dependencies
  - pip install -r requirements.txt

script:
  # Build HTML version of the website
  - make

deploy:
  # Push the built HMTL to Github pages
  - provider: script
    script: doctr deploy . --key-path .github_deploy_key_for_doctr.enc --built-docs _build --deploy-repo santisoler/santisoler.github.io
    skip_cleanup: true
    on:
      branch: master

