site:
  name: Santiago Soler
  author: Santiago Soler
  favicon: images/favicon.svg
  language: en

ignore:
  - "README.md"
  - "css/*.md"
  - "css/academicons/README.md"
  - "environment.yml"
  - "requirements.txt"
  - "LICENSE.md"

home_image:
  image: images/about.jpg
  alt: Profile picture of Santiago Soler in black and white

social:
  - name: Github
    handle: "@santisoler"
    url: https://github.com/santisoler
    icon: fab fa-github
    home: true
  - name: Twitter
    handle: "@santirsoler"
    url: https://twitter.com/santirsoler
    icon: fab fa-twitter
    home: true
  - name: ORCID
    handle: 0000-0001-9202-5317
    url: https://orcid.org/0000-0001-9202-5317
    icon: fab fa-orcid
    home: true
  - name: ResearchGate
    url: https://www.researchgate.net/profile/Santiago-Soler-2
    icon: ai ai-researchgate
  - name: figshare
    url: https://figshare.com/authors/Santiago_Rub_n_Soler/6476147
    icon: ai ai-figshare
  - name: Mail
    handle: santiago.r.soler@gmail.com
    url: mailto:santiago.r.soler@gmail.com
    icon: fas fa-envelope
    home: true
    contact: true
  - name: Website
    handle: www.santisoler.com
    url: https://www.santisoler.com
    icon: fas fa-globe
  - name: GPG Public Key
    url: /santisoler_pub.asc
    icon: fas fa-key
    contact: true
  - name: Telegram
    handle: "@santisoler"
    url: https://t.me/santisoler
    icon: fab fa-telegram-plane
    contact: true
  - name: Matrix
    handle: "@santisoler:matrix.org"
    url: https://matrix.to/#/@santisoler:matrix.org
    icon: fa fa-matrix-org
    contact: true

authors:
  me:
    name: Santiago R. Soler
    url: https://www.santisoler.com/
  agustina:
    name: Agustina Pesce
    url: https://aguspesce.github.io
  andrea:
    name: Andrea Balza Morales
    url: https://www.andreabalza.com/
  guido:
    name: Guido M. Gianni
  mario:
    name: Mario E. Giménez
  leo:
    name: Leonardo Uieda
    url: https://www.leouieda.com/
  rampin:
    name: Rémi Rampin
    url: https://github.com/remram44
  vankemenade:
    name: Hugo van Kemenade
    url: https://github.com/hugovk
  matthewturk:
    name: Matthew Turk
    url: https://github.com/matthewturk
  shapero:
    name: Daniel Shapero
    url: https://github.com/danshapero
  banihirwe:
    name: Anderson Banihirwe
    url: https://github.com/andersy005
  leeman:
    name: John Leeman
    url: https://github.com/jrleeman

licenses:
  cc-by:
    name: Creative Commons Attribution 4.0 International
    slung: CC BY 4.0
    url: https://creativecommons.org/licenses/by/4.0/
  cc-by-sa:
    name: Creative Commons Attribution-ShareAlike 4.0 International
    slung: CC BY-SA 4.0
    url: https://creativecommons.org/licenses/by-sa/4.0/
