name: urubu
channels:
    - conda-forge
dependencies:
    - python=3.6
    - pip
    - doctr
    - jinja2>=2.7
    - beautifulsoup4
    - markdown<3
    - pygments
    - pyyaml
    - pip:
        - https://github.com/jandecaluwe/urubu/archive/master.zip
